remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Hello, I'm Israel.
description: I'm a researcher and programmer. Here are some of my works.
