remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Hello, I'm Israel.
description: <i>I'm a researcher and a programmer. Here are some of my works.</i>
date: 2024-08-21
